### PR TITLE
#2930 make collateral positions easier accessable

### LINKED ISSUE #155: [3.5] Make collateral positions easier accessable #2930
https://github.com/bitshares/bitshares-ui/issues/2930

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes #155

- added collapsed components
- switch margin positions and price feed data
- performed styling

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [x] Light
- [x] Midnight

image

image

image

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Looking good!

**Comment by sschiessl-bcp** [comment]
Please refine
 - Use Ant Table (type="card") for Asset Info Asset Action
 - Make all Asset actions collapsible as well

**Comment by VerevkinAlexander** [comment]
> * Use Ant Table (type="card") for Asset Info Asset Actio

Did you mean Ant Tab?

**Comment by sschiessl-bcp** [comment]
Yes, tabs sorry. Auto-correct.

**Comment by VerevkinAlexander** [comment]
plz review it

**Comment by sschiessl-bcp** [comment]
Forwarded

**Pull request closed without merging**
