### PR TITLE
2499 clearly render proposal contents

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
issue #85

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please adjust the `account_update`

- if it is a proposed operation (fromComponent: "proposed_operation",):
  - [x] if the operation changes any of the active owner or memo keys, then add a red string at the end of the operation description "Dangerous operation!"
To recognize if the keys are changed you need to check the operation payload if active owner or memo is present and changed (see screenshot) as compared to the the currently set permission of the account
image
   - [x] if keys are changed, add those keys in the operation description with "+<public_key>" and "-<public_key" added at the end of the operation description
   - [x] if votes are changed within the account options, display what votes are changed

**Comment by VerevkinAlexander** [comment]
I 

> Please adjust the `account_update`
> 
> * if it is a proposed operation (fromComponent: "proposed_operation",):
>   
>   * [x]  if the operation changes any of the active owner or memo keys, then add a red string at the end of the operation description "Dangerous operation!"
>     To recognize if the keys are changed you need to check the operation payload if active owner or memo is present and changed (see screenshot) as compared to the the currently set permission of the account
>     image
>   * [x]  if keys are changed, add those keys in the operation description with "+<public_key>" and "-<public_key" added at the end of the operation description
>   * [x]  if votes are changed within the account options, display what votes are changed

I`ve implemented this feature, please review it

**Comment by sschiessl-bcp** [comment]
Please also resolve worker proposal names
image

**Comment by sschiessl-bcp** [comment]
I had to adjust the component because it didnt work with key changes. Please investigate my changes. Did it render on your end?

**Comment by VerevkinAlexander** [comment]
I`ve added worker proposal names. I found that we have a problem with render Activity tab on the first launch. That caused because we receive null in response  ChainStore.getObjectsByVoteIds(). I tried to receive a response in promise but had the same result. There are no problems on render Proposed operations tab. Maybe you have any idea why it happens?

**Comment by VerevkinAlexander** [comment]
I found the rendering issue reason. I fixed it, please review.

**Comment by sschiessl-bcp** [comment]
Is this based on develop or https://github.com/blockchainprojects/bitshares-ui/pull/66 ?

**Comment by VerevkinAlexander** [comment]
it is based on develop

**Comment by sschiessl-bcp** [comment]
This will be annoying, but necessary ...

Please rebase against latest develop, and add the new HTLC operations. They have been added in the old format in develop and need to be translated into the new format.

**Comment by VerevkinAlexander** [comment]
I`ve merged the latest changes from develop and add HTLC operations into the new format

**Comment by sschiessl-bcp** [comment]
Accepted

**Pull request closed without merging**
