### PR TITLE
2244 wallet merchant protocol not work(reformated)

### LINKED ISSUE #94: [14.5] #2244 Wallet Merchant
Original issue #2244

Task see https://github.com/bitshares/bitshares-ui/issues/2244#issuecomment-480789973

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
Closes #94 I`ve added invoice component and added routs to App component

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp plz review it

**Comment by sschiessl-bcp** [comment]
I remember we talked about that the button print receipt should always work, even if not paid. Can you double check please?

**Comment by VerevkinAlexander** [comment]
> I remember we talked about that the button print receipt should always work, even if not paid. Can you double check please?

I made only from account exists validation.

**Comment by VerevkinAlexander** [comment]
I`ve deleted all validations

**Comment by sschiessl-bcp** [comment]
Forwarded

**Pull request closed without merging**
