### PR TITLE
#2876 missing vesting balances

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes https://github.com/bitshares/bitshares-ui/issues/2876

Added fetchChain method if the asset was not got
Added user validation for Claim

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
plz review it

**Comment by sschiessl-bcp** [comment]
You yourself have changed this component to table style. Why do you work on the old codebase?

**Comment by VerevkinAlexander** [comment]
Oh, sorry. I`ve used the latest develop for fixing issues as we agreed earlier. I will pick these changes to the branch with changed component

**Comment by sschiessl-bcp** [comment]
> Oh, sorry. I`ve used the latest develop for fixing issues as we agreed earlier. I will pick these changes to the branch with changed component

Is there anything from this PR that still needs to be implemented?

**Comment by StarodubetsWork** [comment]
> > Oh, sorry. I`ve used the latest develop for fixing issues as we agreed earlier. I will pick these changes to the branch with changed component
> 
> Is there anything from this PR that still needs to be implemented?

Add only current account check

**Comment by VerevkinAlexander** [comment]
> > Oh, sorry. I`ve used the latest develop for fixing issues as we agreed earlier. I will pick these changes to the branch with changed component
> 
> Is there anything from this PR that still needs to be implemented?

There is only current account check is needed

**Comment by sschiessl-bcp** [comment]
Ok so we can close this. Current account check is not needed due to multi sig setup.

**Pull request closed without merging**
