### PR TITLE
#2960 Refine wallet merchant protocol

### LINKED ISSUE #169: [14.5] Refine wallet merchant protocol #2960
https://github.com/bitshares/bitshares-ui/issues/2960

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes #169

- Added InoicePay
- Added InvoiceRequest
- Added Qr code for InvoicePay
- Added json validator
- Added Invoice  to the Spotlight

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

image
image

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
For invoice pay, if there is no data present in the link did you add the possibility to scan/enter data in the Pay panel?

**Comment by VerevkinAlexander** [comment]
> For invoice pay, if there is no data present in the link did you add the possibility to scan/enter data in the Pay panel?

There is no way to enter data. I can add some input for invoice string instead of error message when the data string is empty. What do you think?

**Comment by sschiessl-bcp** [comment]
> There is no way to enter data

Absolutely correct. That is why in the specification of the task we have 3 ii.
image

To clarify: if data in address present, use that. if not present, show the enter / scan possibility.

I imagine somehting like shown in Withdraw modal (see the camera icon)
image

If that is hardcoded within the WithdrawModal please create a new ScanOrEnterText component

**Comment by sschiessl-bcp** [comment]
This ready for re-review?

**Comment by goonerDp** [comment]
@sschiessl-bcp, yes. But I think responsive design requires some work, especially for phones. It can take  1-2 hours.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp, yes. But I think responsive design requires some work, especially for phones. It can take 1-2 hours.

**Comment by sschiessl-bcp** [comment]
We will do responsive in separate issue, dont worry for now

**Comment by sschiessl-bcp** [comment]
Please change:
 - 
image Currency is an asset selector with hardcoded list of assets (BTS, bitCNY, bitUSD)
- is `payment QR code` the correct one like indicated in the issue?

**Comment by VerevkinAlexander** [comment]
> is payment QR code the correct one like indicated in the issue?

image


bitshares:operation/transfer?to=<null>&from=<quest11>&asset=<TEST>&amount=<11000>&memo=<Invoice #1234>


image

**Comment by sschiessl-bcp** [comment]
Example to transfer 100 TEST from bitshares account sschiessl to bitshares account test

`bitshares:operation/transfer?to=test&from=sschiessl&asset=TEST&amount=100`

If there is a memo specified

`bitshares:operation/transfer?to=test&from=sschiessl&asset=TEST&amount=100&memo=Some memo`

**Comment by VerevkinAlexander** [comment]
> Example to transfer 100 TEST from bitshares account sschiessl to bitshares account test
> 
> `bitshares:operation/transfer?to=test&from=sschiessl&asset=TEST&amount=100`
> 
> If there is a memo specified
> 
> `bitshares:operation/transfer?to=test&from=sschiessl&asset=TEST&amount=100&memo=Some memo`

thanks

**Comment by VerevkinAlexander** [comment]
fixed, plz check

**Comment by sschiessl-bcp** [comment]
Pay

 - if I scan invalid code twice, view breaks
 - show error message if code invalid
 - I was not able to scan a previously created invoice string, e.g. `8h1jWsPMZ2uEX4TYZesabDNfGbDzaJf4YQ3yPSG1AbVytg7cDkyAdzsKvy8qz1uaLCgj1AkhUsidaT9dazLw42GAx5jscXGYbwRV2EdkHoQzcaNoccwq231UcA7d6aa6K73GPS2uWXDuDVN5JU4c8WHWTA2wF7ghJsfB8zemAcurUwwh17pQXS72FBL7pMmnmtZciJP91`

Request

 - when adding 2 items, then removing one, the plus button does not reappear
 - when user submits, show created string with a readonly textarea or field below to allow copy, with a copy button on the right side

**Comment by VerevkinAlexander** [comment]
> Pay
> 
> * if I scan invalid code twice, view breaks
> * show error message if code invalid
> * I was not able to scan a previously created invoice string, e.g. `8h1jWsPMZ2uEX4TYZesabDNfGbDzaJf4YQ3yPSG1AbVytg7cDkyAdzsKvy8qz1uaLCgj1AkhUsidaT9dazLw42GAx5jscXGYbwRV2EdkHoQzcaNoccwq231UcA7d6aa6K73GPS2uWXDuDVN5JU4c8WHWTA2wF7ghJsfB8zemAcurUwwh17pQXS72FBL7pMmnmtZciJP91`
> 
> Request
> 
> * when adding 2 items, then removing one, the plus button does not reappear
> * when user submits, show created string with a readonly textarea or field below to allow copy, with a copy button on the right side

fixed

**Comment by sschiessl-bcp** [comment]
Accepted

**Pull request closed without merging**
