### PR TITLE
# 2473 Dashboard Portfolio - Trade asset bug

### LINKED ISSUE #98: [5] #2473
Original issue https://github.com/bitshares/bitshares-ui/issues/2473

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes #98

IAdded onMarketChange method on TradingViewPriceChart.jsx start

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
I do the following steps:
- http://localhost:8080/market/OPEN.BTC_BTS
- Click on Dashboard
- Click on Margin Positions
- Click on Market in the bitUSD row
- Observe that the TradingView chart still has the wrong numbers in the y-axis

Please check

**Comment by VerevkinAlexander** [comment]
Looks like TradingView still cached. I fixed please try it

**Comment by sschiessl-bcp** [comment]
When switching from dashboard and back to exchange (also on first load) I get this error 
image

Was that already present before your change? What does it mean? How can it be solved?

**Comment by VerevkinAlexander** [comment]
I can`t reproduce it. Can you give me steps to reproduce? Looks like TradingViewPriceChart calls without quoteSymbol. I added default values for quoteSymbol and baseSymbol, this should help.

**Comment by sschiessl-bcp** [comment]
> I can`t reproduce it. Can you give me steps to reproduce? Looks like TradingViewPriceChart calls without quoteSymbol. I added default values for quoteSymbol and baseSymbol, this should help.

Did you push this change? Also, please rebase

**Comment by VerevkinAlexander** [comment]
Done.

**Comment by sschiessl-bcp** [comment]
Same as https://github.com/blockchainprojects/bitshares-ui/pull/97#issuecomment-506238816

**Comment by VerevkinAlexander** [comment]
Closes because of new PR #152

**Pull request closed without merging**
