### PR TITLE
#2755 show info about pending force settlement orders in account info

### LINKED ISSUE #123: [6.5] #2755 Show info about pending force-settlement orders in account info
https://github.com/bitshares/bitshares-ui/issues/2755

Add a new table below the open orders showing the settle orders.

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes #123

added settlement table 

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

image

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp  Please review it

**Comment by sschiessl-bcp** [comment]
The task was to add this as a second table under open orders, not a new tab. please adjust.

**Comment by VerevkinAlexander** [comment]
> The task was to add this as a second table under open orders, not a new tab. please adjust.

Something like this?
image

**Comment by VerevkinAlexander** [comment]
> The task was to add this as a second table under open orders, not a new tab. please adjust.

Something like this?
image

**Comment by sschiessl-bcp** [comment]
Forwarded

**Pull request closed without merging**
