### PR TITLE
2244 wallet merchant protocol not work

### LINKED ISSUE #94: [14.5] #2244 Wallet Merchant
Original issue #2244

Task see https://github.com/bitshares/bitshares-ui/issues/2244#issuecomment-480789973

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes #94 
I`ve added invoice component and fixed issues with AccountInfo and added routs to App component

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Did you test this after restoring? And if so, how?

If I open this page I see the old page
image

The button does not enable itself even after loggin in (it should be possible to always create the pdf, furthermore clicking on the QR icon on the left side does not work. Please have a look

**Comment by VerevkinAlexander** [comment]
> Did you test this after restoring? And if so, how? 

I have tested it. I created the invoice and pay it using my testnet accounts.
> The button does not enable itself even after loggin in 

It will be enabled after successfully created payment. 

> clicking on the QR icon on the left side does not work

How it should works?

> If I open this page I see the old page

Please give me your vision of how it should looks

**Comment by sschiessl-bcp** [comment]
https://github.com/blockchainprojects/bitshares-ui/issues/94#issuecomment-487545347

Does this work for you locally?

**Comment by VerevkinAlexander** [comment]
> [#94 (comment)](https://github.com/blockchainprojects/bitshares-ui/issues/94#issuecomment-487545347)
> 
> Does this work for you locally?

yes

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp   Please review it.

**Comment by sschiessl-bcp** [comment]
You need to seriously start checking if you are checking in reformatting only files (always revert them and exclude in the commit if you see one). This caused the conflict that present. 
image


Will resolve now

**Comment by sschiessl-bcp** [comment]
This PR contains reformatting only changes for 
 - app/api/ApplicationApi.js
 - app/components/Account/AccountAssetCreate.jsx
 - app/components/Account/AccountAssetUpdate.jsx
 - app/components/Account/AccountPortfolioList.jsx 
 - app/components/Account/AccountSelector.jsx
 - app/components/Account/CreateAccount.jsx 
 - app/components/Account/Proposals.jsx
 - app/components/Account/VotingAccountsList.jsx
 - app/components/Blockchain/OperationAnt.js 
 - app/components/Blockchain/ProposedOperation.jsx
 - app/components/Blockchain/operations/AccountWhitelist.jsx
 - app/components/Exchange/BuySell.jsx
 - app/components/Exchange/Exchange.jsx 
 - app/components/Exchange/ExchangeHeader.jsx
 - app/components/Exchange/MyOpenOrders.jsx 
 - app/components/Exchange/Personalize.jsx
 - app/components/Layout/Footer.jsx
 - app/components/Modal/BorrowModal.jsx
 - app/components/Modal/DirectDebitClaimModal.jsx 
 - app/components/Modal/DirectDebitModal.jsx
 - app/components/Modal/HtlcModal.jsx
 - app/components/Modal/SendModal.jsx
 - app/components/News.jsx 
 - app/components/Settings/SettingsEntry.jsx
 - app/components/Showcases/DirectDebit.jsx
 - app/components/Showcases/Htlc.jsx
 - app/components/Utility/AssetName.jsx
 - app/components/Utility/LoadingButton.jsx
 - app/components/Utility/withWorthLessSettlementFlag.jsx
 - app/lib/common/MarketClasses.js
 - app/lib/common/market_utils.js
 - app/stores/AccountStore.js 

This is not acceptable. Please create a new feature branch off of latest develop and include the actual changes for the issue and create a new PR

**Pull request closed without merging**
