### PR TITLE
Exchange page, my open orders, wrong price direction

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
Fixed <key>, <td>, <option> <select> issues
Issue: #42

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
please review it

**Comment by sschiessl-bcp** [comment]
What are the actual changes in app/components/Exchange/OrderBook.jsx ?
It's hard to see with the reformatting

**Comment by VerevkinAlexander** [comment]
I added key  https://github.com/blockchainprojects/bitshares-ui/pull/49/commits/1d732c453683f2437657f8953c43767f11ce0df8#diff-3aaa4fc021c75bd17e1e59adb802e56dR2772 
https://github.com/blockchainprojects/bitshares-ui/pull/49/commits/1d732c453683f2437657f8953c43767f11ce0df8#diff-3aaa4fc021c75bd17e1e59adb802e56dR2739

I changed num type to string type https://github.com/blockchainprojects/bitshares-ui/pull/49/commits/1d732c453683f2437657f8953c43767f11ce0df8#diff-4f6322a6f00cbf223233779843027172R348
https://github.com/blockchainprojects/bitshares-ui/pull/49/commits/1d732c453683f2437657f8953c43767f11ce0df8#diff-4f6322a6f00cbf223233779843027172R352
But it is created new issue with misssing default values on Personalize screen

I rewrite block to use  to stiky-table block instead of `<td>`
https://github.com/blockchainprojects/bitshares-ui/pull/49/commits/1d732c453683f2437657f8953c43767f11ce0df8#diff-4f6322a6f00cbf223233779843027172R1252

I deleted `<span>` block
https://github.com/blockchainprojects/bitshares-ui/pull/49/commits/1d732c453683f2437657f8953c43767f11ce0df8#diff-92ef74e713a293d6b91ab791e6e21853R75

**Comment by sschiessl-bcp** [comment]
> But it is created new issue with misssing default values on Personalize screen

What is that issue? Is it fixable?

**Comment by sschiessl-bcp** [comment]
I assume you mean this one?
image

**Comment by VerevkinAlexander** [comment]
Yes I mean this issue. It is fixable but it will make a huge impact

**Comment by sschiessl-bcp** [comment]
Do you see any alternatives to fix the original issue without causing new issues?

**Comment by VerevkinAlexander** [comment]
It needs some additional time to research.

**Comment by sschiessl-bcp** [comment]
> It needs some additional time to research.

Please do, but don't let it explode (suggestion max. 4 hours)

**Comment by VerevkinAlexander** [comment]
I fixed it. Please review it.

**Comment by sschiessl-bcp** [comment]
Approved and forwarded

**Pull request closed without merging**
