### PR TITLE
[Merged] Handle proposals related to phishing accounts #23

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
Added method isSucpicious in Proposals and Checkbox to AccountOverview

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
I finished that task. Please review it when you have time.

**Comment by sschiessl-bcp** [comment]
Please always reference the associated issue #23

**Review by sschiessl-bcp — CHANGES_REQUESTED** [review]
- Remove "Deactivate suspicious proposals" toggle from "Portfolio"
- Please use the new bitshares-style-guide components (Switch would be appropriate). Also optimize the positioning of it such that it somewhat fits the UI

As a new feature, please add a "Possible Scam" indicator where the "Approve" button was before, that shows the scam message returned by "isKnownScammer" onHover

**Comment by sschiessl-bcp** [comment]
Blocked by https://github.com/blockchainprojects/bitshares-ui/issues/43

**Comment by VerevkinAlexander** [comment]
> Blocked by #43

I added ids please review it

**Comment by sschiessl-bcp** [comment]
Accepted and forwarded.

**Pull request closed without merging**
