### PR TITLE
#2643 Basic HTLC support

### LINKED ISSUE #104: [18] #2643 Basic HTLC support
https://github.com/bitshares/bitshares-ui/issues/2643

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes #104
Added htlc modal and htlc components

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

image

image

image

image

image

- [ ] Dark
- [ ] Light
- [ ] Midnight

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Here is my feedback:

- Preimage size is the size of the secret, not the hash
- Please adjust the PreImage section to the following
image
  - Don't mind the exact margins and styling in the mockup, use the normal defaults here
  - The cube icon does not exist yet, use any existing icon and I will add the proper one
  - The cube button creates a new random string 
  - The upper copy button copies the secret and used hash into clipboard
  - The lower copy button copies the hash and size into clipboard
  - The edit button in the header allows the user to enter its own secret 
  - Expiration has preselects "One Day" Two Days" "One Week", which means . The preselect "One Day" is used as default, and if it is used it is highlighted (differnt color). User can still use datepicker if desired.

**Comment by sschiessl-bcp** [comment]
Forgot this one

 - The search button should search htlc id, from, to and hash

**Comment by VerevkinAlexander** [comment]
on redeem htlc
image

**Comment by sschiessl-bcp** [comment]
> on redeem htlc
> image

I ll check that error, skip for now

**Comment by VerevkinAlexander** [comment]
Also on the extend_htlc  operation always added only 0 seconds

**Comment by sschiessl-bcp** [comment]
Weird... Will need to debug. Please finish it until that and push, I will have a look tomorrow

**Comment by VerevkinAlexander** [comment]
I`ve finished it. Please look.

**Comment by sschiessl-bcp** [comment]
Accepted, please check my above commits.

Remarks in general:
 - Make sure props are always defined, set as required or with defaults where needed
 - The way the components are rendered is complicated (I know this is copied from SendModal, still)
 - When creating a new component, always check that the amounts of re-renders is minimized
 - Modals should never listen to currentAccount, but instead receive the target account via props. In that case I added `fromAccount` to the modal
 - I found several unused variables and props, please be more thorough here

**Pull request closed without merging**
