### PR TITLE
#128 Removed charting_library sources

### LINKED ISSUE #128: [3] #2826 Remove charting library from github
https://github.com/bitshares/bitshares-ui/issues/2826

### PR DESCRIPTION
**Pull request by Metizik**
<h2>General</h2>
Closes #128 

1. Created script (npm run package-charting-library) that archives the source code content of the charting_library folder into one file (content as it is right now, .zip or .tar or whatever is easiest, I don't want many additional dependencies, and all dependencies should be devDependencies) and writes the .md5 file for the archive
2. Create script (npm run install-charting-library) that 
  downloads the previously packaged file from an external URL`https://bitshares.org/assets/charting_library.zip`
  verifies the downloaded file against the .md5 file checksum
  unpacks it such that the charting_library folder is fully restored locally
3. Deleted source code within the charting_library folder
4. Added postinstall script to npm to set up charting library from remote assets

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Can you please comment on the new dependencies and why they are needed

**Comment by mettizik** [comment]
@sschiessl-bcp , sure:
* `archiver` is used to compress sources of charting_library into zip file
* `extract-zip` is used to decompress downloaded zip file, since `archiver` can only compress files
* `https` is used to download file over HTTPS URL from assets
* `md5-file` is used to calculate MD5 digest and verify the downloaded file

**Comment by sschiessl-bcp** [comment]
`extract-zip` is not able to also compress? Two dependencies seem over the top. Isn't there one (that is properly maintained) that can do both?

**Comment by mettizik** [comment]
`extract-zip` is not able to compress. Most relevant node modules related to ZIP compression are all splitted into zippers and unzippers separately, the only found alternative would be to use `zlib` module, but it requires much more logic with manual iterating over files, excluding files we want to skip and combining separate zipped files streams into single write stream there is an example of GZip https://medium.com/@harrietty/zipping-and-unzipping-files-with-nodejs-375d2750c5e4

Another possible implementation will be to use TAR and ZIP, but it does not match current assets/charting_library.zip format of archive

**Comment by sschiessl-bcp** [comment]
Thanks

**Pull request closed without merging**
