### PR TITLE
84 implement recurring payment direct debit mandate

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
issue #84

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp, please, note that for proper work of DatePicker component, the latest version of Antd is needed.

**Comment by sschiessl-bcp** [comment]
Which version do we have, which do we need?

**Comment by VerevkinAlexander** [comment]
> 
> 
> Which version do we have, which do we need?

"bitshares-ui-style-guide" requires: antd": "^3.10.0".
On this version, I spotted issues with selecting of time in DatePicker. On "3.14.1" everything is ok.

**Comment by sschiessl-bcp** [comment]
> > Which version do we have, which do we need?
> 
> "bitshares-ui-style-guide" requires: antd": "^3.10.0".
> On this version, I spotted issues with selecting of time in DatePicker. On "3.14.1" everything is ok.

Will be in next style guide update!

**Comment by sschiessl-bcp** [comment]
Accepted and forwarded

**Pull request closed without merging**
