### PR TITLE
Integration Testing - Edge Browser stuck on Loading

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
Updated alt and alt-container changed webpack.config
Issue #52

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp please review it

**Comment by sschiessl-bcp** [comment]
I'm getting compilation errros, anything I need to be aware of?

**Comment by VerevkinAlexander** [comment]
Please try to delete node_modules, package-lock file and reinstall packages

**Comment by sschiessl-bcp** [comment]
I could compile it now, but Edge still does not load the UI. 

This error occurs
image

Does it load on your end?

**Comment by VerevkinAlexander** [comment]
Yes, it is work for me. My environment:  Edge 42.17134.1.0,  Windows 10, npm package manager

**Comment by sschiessl-bcp** [comment]
More effort needed here, pausing for now

**Comment by sschiessl-bcp** [comment]
closed, wont be supporting edge since they will switch their framework

**Pull request closed without merging**
