### PR TITLE
#2973 simplified order form for ordinary users

### LINKED ISSUE #2973: Simplified order form for ordinary users (i.e. non-traders)
It would be very useful and would promote adoption if the wallet offered a simplified form for ordinary users (i.e. non-traders) to convert one token to another WITHOUT an orderbook by simply specifying a) the token they have, b) the token they want, and c) a quantity. 

To date, it has not been feasible to offer such a UI for the DEX due to lack of liquidity. However, with arbitrage / mirrored liquidity feature coming to DexBot soon, this type of UI could offer a far better user experience than previously possible.

Of course, even with improved liquidity, not all markets will have sufficient liquidity at all times. But by giving feedback to the user about e.g. how their average price would compare to the current best price, even a beginning user could make an intelligent decision about whether to proceed.

The user could even be presented with the option to essentially place a limit order (even though they wouldn't see the orderbook), with the proviso that the order would likely not get filled instantly (or might not be filled completely). For example, by placing a buy order with a price perhaps slightly above the best ask (or a sell order with a price slightly below the best bid), it would fill partially and then the remaining shares should present an arbitrage opportunity that can be taken advantage of by DexBots monitoring that market, thus filling the rest of the order and completing the user's requested conversion.

I strongly believe the lack of this type of user-friendly UI is one of the factors contributing to low adoption rate of the DEX. 

Thoughts?

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
<h2>General</h2>
Closes #2973 

I've implemented a new component QuickTrade.
To open it you can go to http://localhost:8080/quick-trade or you can push the button QuickTrade in Dashboard->Activity->click on any currency pair: 

quicktrade2

quicktrade

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Check comment here https://github.com/bitshares/bitshares-ui/pull/3037#issuecomment-522066143

**Comment by sschiessl-bcp** [comment]
You accidently opened the PR against bitshares repo, I opened a new one here

**Comment by Metizik** [comment]
I have performed a components replacement for those that use style-guide.
I also performed dev testing:
1) I have compared several markets in my new UI with the values that the Exchange tab shows
2) I entered zero and large values in the fields for entering the quantity. 
When entering zero, zero is displayed in the opposite amount field
When entering a large value in the sell amount field, the market depth is displayed in the reсeive amount field
When entering a large value in the reсeive amount field, Infinity is now displayed in the sell amount field

Sell Asset selector displays a list of assets that are on the balance of the current user.
Receive Asset selector initially displays the same list, but the user can write in the search field the asset he is interested in. I decided to do so that the whole list of assets would not load at once. The user needs to enter at least three characters to start the search. I have added a tooltip that tells this.

The total fee percentage is calculated as the sum of the market fee as a percentage and the transaction fee as a percentage. Is this correct?
@sschiessl-bcp

**Comment by sschiessl-bcp** [comment]
- if only one asset is selected, selector should not disable automatically
 - have a look at the margins hear and streamline 
image
 - if user selects as asset to sell the asset that is currently locked in as to receive, switch assets
 - is the liquidity penalty calculated correctly?
 - please enable a switch like we have in debt column of margin position overview, if I click on an entry in the row "AMOUNT (CNY)" in orders it switches to "<SUMICON> AMOUNT (CNY)" and shows cumulative sums.
 - add price base and quote in the header of orders and in the price collapser
 - the down arrow of the collapser component is hidden by the ttext
 - i added the icon "instant-trade". please create a new Spotlight tile (use dummy translations)

**Comment by Metizik** [comment]
@sschiessl-bcp , working on. Can you, please, clarify these points:
> if user selects as asset to sell the asset that is currently locked in as to receive, switch assets

I don't actually understand - we want to reset fields of asset to receive, if user selects the same asset to sell, right?

> is the liquidity penalty calculated correctly?

I used the formulas you provided to calculate the liquidity penalty: https://github.com/bitshares/bitshares-ui/issues/2973#issuecomment-518204343 It seems to be ok.
If there is an specific way to check this - I will recheck.

> please enable a switch like we have in debt column of margin position overview, if I click on an entry in the row "AMOUNT (CNY)" in orders it switches to " AMOUNT (CNY)" and shows cumulative sums. 

I am not sure I will be able to complete this point today.

Rest of points is understood and now in progress

**Comment by sschiessl-bcp** [comment]
Assume transaction fee is paid in sellAsset.

Please refactor to reduce code duplication:
1. add method `_getTransactionFee(denominationAsset)` and use where transaction fee needs to be calculated. If `denomincationAsset` is sellAsset object, then return fee as denominated in sellAsset. If it is receiveAsset, then return transaction fee as denominated in receiveAsset. For that, calculate sellAsset fee, and use last market price to do the conversion (because we pay the actual fee in sellAsset, this is just a guess via market price). default is sellAsset denomination
2. add method `_getMarketFee(denomindatedAsset)` with the same logic (default denomination is receiveAsset, since market fee only applies to receive asset)
3. refactor such that view and internal numbers are streamlines. For example: variables of percent should always carry a value from 0 to 1 (and not 100). Do the covnersion into string % only in the render parts (e.g. `getTotalPercentFee` should return a value between 0 and 1, conversion into string % happens in the view 
4. `getTotalPercentFee` also needs to include the liquidty penalty (use the one with respect to market price)
5. something weird is happening when calculating amount
image
image
image
Notice how the second picture has a higher price, and then price goes down again in third picture. Matching of orders needs to be done sorted from best to worst price.
6. if there is no exact asset match, please display the icon "unknown" (i just added it)

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp , working on. Can you, please, clarify these points:
> 
> > if user selects as asset to sell the asset that is currently locked in as to receive, switch assets
> 
> I don't actually understand - we want to reset fields of asset to receive, if user selects the same asset to sell, right?

If user has: to sell BTS, to receive bitCNY, and now selects bitCNY in the to sell combobox, swap assets. Please implement.

> > is the liquidity penalty calculated correctly?
> 
> I used the formulas you provided to calculate the liquidity penalty: [bitshares#2973 (comment)](https://github.com/bitshares/bitshares-ui/issues/2973#issuecomment-518204343) It seems to be ok.
> If there is an specific way to check this - I will recheck.

I fixed it, was visualization problem

**Comment by Metizik** [comment]
@sschiessl-bcp , will do. Can you please explain, what is the reason behind points 1 and 2, so that I did it right next time on the first pass?

**Comment by sschiessl-bcp** [comment]
> Can you please explain, what is the reason behind points 1 and 2, so that I did it right next time on the first pass?

The reason is the ability to display the cost of the transaction in whatever asset the user pleases, while the actual fees are still paid in either the receiving asset for market fee and mostly BTS for transaction fee. I want to be able to carry a notion of X% of total fee, and then it makes sense only if all fees can be denominated in the same asset

**Comment by sschiessl-bcp** [comment]
- Assume I have asset to sell and receive selected, and amounts entered. 
   - If I change the asset to sell, the amount of asset to receive should remain and not be reset, and the correct amount for asset to sell recalculated. Same goes other way around
   - When swapping assets, amount should also be persisted (amounts are also swapped, and not removed)
 - only show feedprice if the chosen assets are bitassets with its collateral (e.g. bitCNY and BTS)
 - the orders should per default subscribe to the market and update itself when order book is updated (just like in exchange). implement a toggle "subscribe to market" within the collapsed component that user can uncheck and subscription is halted and he can inspect the orders

**Comment by sschiessl-bcp** [comment]
image

image

image

image

**Comment by sschiessl-bcp** [comment]
Forwarded.

**Pull request closed without merging**
