### PR TITLE
500 page

### PR DESCRIPTION
**Pull request by yuriikarpenkoo**

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please include in the initial description which issue this pull request solves.

**Comment by sschiessl-bcp** [comment]
When there is an exception, the whole UI reloads. Can this be changed such that the app does not reload but redirects to "/error".

You can for example add a test exception to https://github.com/blockchainprojects/bitshares-ui/blob/c5016f8a0b15d5b0dedc51b1d69ad4a07f1a8018/app/components/Account/CreateAccountPassword.jsx#L236
i.e.
image

Then click on Menu -> Create Account. Observe that the UI reloads before routing to "/error"

**Comment by sschiessl-bcp** [comment]
The UI is still reloading in the above mentioned case.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp I created page 500 as a wrapper for the app  ui . Please review this solution. 
This branch is obsolete. Should I merge changes from debug report branch to this branch or from develop after merging with debug report branch?

**Comment by sschiessl-bcp** [comment]
>  I created page 500 as a wrapper for the app ui. This branch is obsolete

@VerevkinAlexander Which branch is with your solution?

**Comment by sschiessl-bcp** [comment]
@VerevkinAlexander please create a PR with your solution

**Pull request closed without merging**
