### PR TITLE
Updated Vesting Balances to Table Style

### LINKED ISSUE #165: [3] Update Vesting Balances to Table Style #2979
https://github.com/bitshares/bitshares-ui/issues/2979

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
<h2>General</h2>
Closes #165 

Updated Vesting Balances to Table Style

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please check one time that you only refactored the view, and that all logic is matching with the current develop branch in bitshares. Confirm back here.

**Comment by VerevkinAlexander** [comment]
I have checked and it looks like everything's okay.

**Comment by sschiessl-bcp** [comment]
Forwarded

**Comment by sschiessl-bcp** [comment]
> I have checked and it looks like everything's okay.

You have not compared to the latest develop branch, there are differences. 

You need to be more carefull next time!

**Comment by sschiessl-bcp** [comment]
Sorry, misunderstood something. All good.

**Pull request closed without merging**
