### PR TITLE
2311 dashboard portfolio columns

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
I completed implementation, please review it 
Issue: #60

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
please resolve the conflict

**Comment by VerevkinAlexander** [comment]
ok , I will fix it asap

**Comment by VerevkinAlexander** [comment]
I`ve fixed issues with tr and div elements. Also, I`ve fixed the issue with the crash on Activity tab. The reason for the crash was that some actions have different market directions, so I added Store listener to watch on market directions. During fixing, I found that Open order did not display on the Open orders tab so I`ve added ant table to it. I`ve spent 8 real hours on it.

**Comment by VerevkinAlexander** [comment]
Please review it

**Comment by sschiessl-bcp** [comment]
The old table could compress itself hiding certaing columns if the window is too small, see here
image


Please investigate if ANT table allows that too

**Comment by VerevkinAlexander** [comment]
> 
> 
> The old table could compress itself hiding certaing columns if the window is too small, see here
> image
> 
> Please investigate if ANT table allows that too


In the old table, hiding certain columns was done manually. Unfortunately in antd it's also the only option.
I have added "column-hide-small" class where necessary.

**Comment by sschiessl-bcp** [comment]
image

There is nothing shown on the favorite section now, yet the pagination component suggests there is plenty. Please check @VerevkinAlexander

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 
The problem occurred because "MarketsTable" component depends on "PaginatedList" which was modified previously for switching to "bitshares-ui-style-guide" Table. So I created "PaginatedListOld" component which fixes "MarketsTable".
Should I rewrite "MarketsTable" for using "bitshares-ui-style-guide" Table?

**Comment by sschiessl-bcp** [comment]
What other components use PaginatedList, and would require the "Old" way?

**Comment by VerevkinAlexander** [comment]
Assets (/explorer/assets) after selecting "Prediction market assets".

**Comment by sschiessl-bcp** [comment]
> Assets (/explorer/assets) after selecting "Prediction market assets".

Thanks.

Please refactors Assets and MarketTable to use the new PaginatedList. For MarketsTable this might require that you integrate MarketsRow into the MarketTable class to stick to the new dataSource format.

**Comment by VerevkinAlexander** [comment]
I refactored MarketTable, changed data structure, to use the new PaginatedList. For Assets, I decided to use Antd List component instead of PaginatedList. Also, I merged the latest changed from develop branch. Please review my solution. Maybe we should add Antd List to the bitshares-ui-style-guide?

**Comment by sschiessl-bcp** [comment]
> I refactored MarketTable, changed data structure, to use the new PaginatedList. For Assets, I decided to use Antd List component instead of PaginatedList. Also, I merged the latest changed from develop branch. Please review my solution. Maybe we should add Antd List to the bitshares-ui-style-guide?

Where is that list used?

**Comment by sschiessl-bcp** [comment]
When there is no data in the list it displays
image

Please notice that the text "No Data" is falling off of the bottom of the component. Please adjust such that the image has enough space

**Comment by VerevkinAlexander** [comment]
> Where is that list used?

It used on Explorer tab => prediction market assets

**Comment by VerevkinAlexander** [comment]
> When there is no data in the list it displays
> image
> 
> Please notice that the text "No Data" is falling off of the bottom of the component. Please adjust such that the image has enough space

ok. I will do it asap

**Comment by sschiessl-bcp** [comment]
1. Please adjust the visuals

image

The table should be aligned like in the picture for Open Orders and activity as well.

2. Adjust the combobox to be using styleguide
image

3. If table doesnt fit, enable scrollbar
image

4. It seems that the footer does not have to correct number of cells when the screen is smaller
image

**Comment by StarodubetsWork** [comment]
> 1. Please adjust the visuals
> 
> image
> 
> The table should be aligned like in the picture for Open Orders and activity as well.
> 
> 1. Adjust the combobox to be using styleguide
>    image
> 2. If table doesnt fit, enable scrollbar
>    image
> 3. It seems that the footer does not have to correct number of cells when the screen is smaller
>    image

I fixed it, please review it

**Comment by VerevkinAlexander** [comment]
I fixed it, please review it

**Comment by sschiessl-bcp** [comment]
Forwarded.

**Pull request closed without merging**
