### PR TITLE
[Merged] Changed Fraction to BigNumber

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
Isse #16 

I changed fraction library to bignumber. But after 1e-8 it still works incorrectly

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please comment with the respect to the original issue and the expected behavior.

What was improved? What works now as expected?

**Comment by VerevkinAlexander** [comment]
> What was improved? What works now as expected?
the issue with length does not appear.
Now we can input any small number and can operate with  0.0000001 and multiplying works correctly till total is more 1e-8

**Comment by sschiessl-bcp** [comment]
The maximum number of accuracy is 1e-8. So if that works, it's perfect as more is not needed!

**Comment by sschiessl-bcp** [comment]
Accepted, will forward it!

**Pull request closed without merging**
