### PR TITLE
137 fixed Htlc updates after creation / update

### LINKED ISSUE #137: HTLC - the HTLC list isn't updated after creating a new HTLC #2886
https://github.com/bitshares/bitshares-ui/issues/2886

Issue is that its not connected to listen to blockchain change (e.g. like the dashboard which automatically shows incoming balance changes)

### PR DESCRIPTION
**Pull request by Metizik**
<h2>General</h2>
Closes #137 

I tryed to subscribe to blockchain updates to handle these updates automatically but did not manage to make it work correctly in this way - no update events were received in component.
Regarding this I added a callback, used in `HtlcModal` to notify parent component about changes made. It still had some issues, when got called right after operation completed, so I deferred it by 1s on forceUpdate.

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [x] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
@VerevkinAlexander 

The new update of the backend **should** deliver htlcs of a user within the full account. Please try https://github.com/bitshares/bitsharesjs/blob/554c9192139761fa833de80a560893940bd5bcaa/lib/chain/src/ChainStore.js#L921 and check if the return value directly contains HTLC. And if so, please add the htlc in the same way as https://github.com/bitshares/bitsharesjs/blob/554c9192139761fa833de80a560893940bd5bcaa/lib/chain/src/ChainStore.js#L1010 is added in https://github.com/blockchainprojects/bitsharesjs

Then use that in here.

**Comment by VerevkinAlexander** [comment]
> @VerevkinAlexander
> 
> The new update of the backend **should** deliver htlcs of a user within the full account. Please try https://github.com/bitshares/bitsharesjs/blob/554c9192139761fa833de80a560893940bd5bcaa/lib/chain/src/ChainStore.js#L921 and check if the return value directly contains HTLC. And if so, please add the htlc in the same way as https://github.com/bitshares/bitsharesjs/blob/554c9192139761fa833de80a560893940bd5bcaa/lib/chain/src/ChainStore.js#L1010 is added in https://github.com/blockchainprojects/bitsharesjs
> 
> Then use that in here.

done

**Comment by sschiessl-bcp** [comment]
Dependency is https://github.com/blockchainprojects/bitsharesjs/pull/1

**Comment by sschiessl-bcp** [comment]
@VerevkinAlexander 

What node have you connected to to test `ChainStore.fetchFullAccount(accountId).get("htlcs");`?

**Comment by VerevkinAlexander** [comment]
I tested it locally

**Comment by sschiessl-bcp** [comment]
> I tested it locally

Did you ever see orders? What node did you connect to?

Your changes to bitsharesjs do not match what core provides, see https://github.com/bitshares/bitsharesjs/commit/e1384a52ab44f0a9d1f617c386403edd1ebd37b8

**Comment by VerevkinAlexander** [comment]
> > I tested it locally
> 
> Did you ever see orders? What node did you connect to?
> 
> Your changes to bitsharesjs do not match what core provides, see [bitshares/bitsharesjs@e1384a5](https://github.com/bitshares/bitsharesjs/commit/e1384a52ab44f0a9d1f617c386403edd1ebd37b8)

Yes,  I saw orders and there is was only htlc variable, no form_htlcs or to_htlcs were present there. I do not remember which node it was, but I'm sure on 200%, I`ve tested it with this variable!

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp should we do come thing with it or it can be closed?

**Comment by sschiessl-bcp** [comment]
This needs checking by me first

**Comment by sschiessl-bcp** [comment]
Time spent: 8 hours.

**Comment by sschiessl-bcp** [comment]
Forwarded.

**Pull request closed without merging**
