### PR TITLE
2473 dashboard portfolio trade asset bug(reformated)

### LINKED ISSUE #98: [5] #2473
Original issue https://github.com/bitshares/bitshares-ui/issues/2473

### PR DESCRIPTION
**Pull request by VerevkinAlexander**
Closes #98
IAdded onMarketChange method on TradingViewPriceChart.jsx start

### CODE REVIEW

**Comment by VerevkinAlexander** [comment]
Please review it

**Comment by sschiessl-bcp** [comment]
Did you manually test the necessity of all the switchMarket calls? Every call increases the overhead onto the node.

**Comment by VerevkinAlexander** [comment]
> Did you manually test the necessity of all the switchMarket calls? Every call increases the overhead onto the node.
yes, I`ve tested them manually. I did not find a solution without using switchMarket call

**Comment by sschiessl-bcp** [comment]
Please provide a screenshot of every click/link action that required to add switchMarkets.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp

**Comment by sschiessl-bcp** [comment]
You provided me three screens, but added the switch to over 10 spots in the code. Please elaborate

**Comment by VerevkinAlexander** [comment]
FormattedPrice

I've done additional testing and found the ways to optimize the solution: some unnecessary function calls which were removed. The bug has been reproduced from four places, so I left the function calls only in these four files and posted four relevant screenshots.
Perhaps this problem could be solved in another way, but it will take more time to research.

**Comment by sschiessl-bcp** [comment]
Done

**Pull request closed without merging**
